### SQLAlchemy ORM - Declaring Mapping

The main objective of the Object Relational Mapper API of SQLAlchemy is to facilitate associating user-defined Python classes with database tables, and objects of those classes with rows in their corresponding tables.

The ORM is constructed on top of the SQL Expression Language. It is a high level and abstracted pattern of usage. In fact, ORM is an applied usage of the Expression Language.

### Declare Mapping

First of all, create_engine() function is called to set up an engine object which is subsequently used to perform SQL operations. The function has two arguments, one is the name of database and other is an echo parameter when set to True will generate the activity log.

The Engine establishes a real DBAPI connection to the database when a method like Engine.execute() or Engine.connect() is called. It is then used to emit the SQLORM which does not use the Engine directly; instead, it is used behind the scenes by the ORM.

**A base class stores a catlog of classes and mapped tables in the Declarative system. This is called as the declarative base class. There will be usually just one instance of this base in a commonly imported module. The declarative_base() function is used to create base class. This function is defined in sqlalchemy.ext.declarative module.**

Once base classis declared, any number of mapped classes can be defined in terms of it. Following code defines a Customer’s class. It contains the table to be mapped to, and names and datatypes of columns in it.

A class in Declarative must have a __tablename__ attribute, and at least one Column which is part of a primary key. Declarative replaces all the Column objects with special Python accessors known as descriptors.

Each Table object is a member of larger collection known as MetaData and this object is available using the .metadata attribute of declarative base class. The MetaData.create_all() method is, passing in our Engine as a source of database connectivity.

### SQLAlchemy ORM - Creating Session

In order to interact with the database, we need to obtain its handle. A session object is the handle to database. Session class is defined using sessionmaker() – a configurable session factory method which is bound to the engine object created earlier.

Sr.No.	Method & Description
1	
begin()

begins a transaction on this session

2	
add()

places an object in the session. Its state is persisted in the database on next flush operation

3	
add_all()

adds a collection of objects to the session

4	
commit()

flushes all items and any transaction in progress

5	
delete()

marks a transaction as deleted

6	
execute()

executes a SQL expression

7	
expire()

marks attributes of an instance as out of date

8	
flush()

flushes all object changes to the database

9	
invalidate()

closes the session using connection invalidation

10	
rollback()

rolls back the current transaction in progress

11	
close()

Closes current session by clearing all items and ending any transaction in progress

### SQLAlchemy ORM - Using Query

All SELECT statements generated by SQLAlchemy ORM are constructed by Query object. It provides a generative interface, hence successive calls return a new Query object, a copy of the former with additional criteria and options associated with it.

Query objects are initially generated using the query() method of the Session as follows −

q = session.query(mapped class)

The query object has all() method which returns a resultset in the form of list of objects. If we execute it on our customers table −

result = session.query(Customers).all()


Sr.No.	Method & Description
1	
add_columns()

It adds one or more column expressions to the list of result columns to be returned.

2	
add_entity()

It adds a mapped entity to the list of result columns to be returned.

3	
count()

It returns a count of rows this Query would return.

4	
delete()

It performs a bulk delete query. Deletes rows matched by this query from the database.

5	
distinct()

It applies a DISTINCT clause to the query and return the newly resulting Query.

6	
filter()

It applies the given filtering criterion to a copy of this Query, using SQL expressions.

7	
first()

It returns the first result of this Query or None if the result doesn’t contain any row.

8	
get()

It returns an instance based on the given primary key identifier providing direct access to the identity map of the owning Session.

9	
group_by()

It applies one or more GROUP BY criterion to the query and return the newly resulting Query

10	
join()

It creates a SQL JOIN against this Query object’s criterion and apply generatively, returning the newly resulting Query.

11	
one()

It returns exactly one result or raise an exception.

12	
order_by()

It applies one or more ORDER BY criterion to the query and returns the newly resulting Query.

13	
update()

It performs a bulk update query and updates rows matched by this query in the database.

### SQLAlchemy ORM - Updating Objects

To modify data of a certain attribute of any object, we have to assign new value to it and commit the changes to make the change persistent.

Let us fetch an object from the table whose primary key identifier, in our Customers table with ID=2. We can use get() method of session as follows −

x = session.query(Customers).get(2)

x.address = 'Banjara Hills Secunderabad'
session.commit()

The change will be persistently reflected in the database. Now we fetch object corresponding to first row in the table by using first() method as follows −

x = session.query(Customers).first()

x.name = 'chirag'
print ("Name: ", x.name, "Address:", x.address, "Email:", x.email)

Even though the change is displayed, it is not committed. You can retain the earlier persistent position by using rollback() method with the code below.

session.rollback()

For bulk updates, we shall use update() method of the Query object. Let us try and give a prefix, ‘Mr.’ to name in each row (except ID = 2). The corresponding update() statement is as follows −

session.query(Customers).filter(Customers.id! = 2).
update({Customers.name: f"Mr.{Customers.name}"}, synchronize_session = False)

#### The update() method requires two parameters as follows −

A dictionary of key-values with key being the attribute to be updated, and value being the new contents of attribute.

synchronize_session attribute mentioning the strategy to update attributes in the session. Valid values are false: for not synchronizing the session, fetch: performs a select query before the update to find objects that are matched by the update query; and evaluate: evaluate criteria on objects in the session.

### SQLAlchemy ORM - Applying Filter

Resultset represented by Query object can be subjected to certain criteria by using filter() method. The general usage of filter method is as follows −

session.query(class).filter(criteria)

### Filter Operators

### Equals
The usual operator used is == and it applies the criteria to check equality.

result = session.query(Customers).filter(Customers.id == 2)

### Not Equals
The operator used for not equals is != and it provides not equals criteria.

result = session.query(Customers).filter(Customers.id! = 2)

### Like
like() method itself produces the LIKE criteria for WHERE clause in the SELECT expression.

result = session.query(Customers).filter(Customers.name.like('Ra%'))

### IN
This operator checks whether the column value belongs to a collection of items in a list. It is provided by in_() method.

result = session.query(Customers).filter(Customers.id.in_([1,3]))
for row in result:

### AND
This conjunction is generated by either putting multiple commas separated criteria in the filter or using and_() method as given below −

result = session.query(Customers).filter(Customers.id>2, Customers.name.like('Ra%'))

### OR
This conjunction is implemented by or_() method.

from sqlalchemy import or_
result = session.query(Customers).filter(or_(Customers.id>2, Customers.name.like('Ra%')))

### Returning List and Scalars

### all()
It returns a list. Given below is the line of code for all() function.

session.query(Customers).all()

### first()
It applies a limit of one and returns the first result as a scalar.

### one()
This command fully fetches all rows, and if there is not exactly one object identity or composite row present in the result, it raises an error.